# استفاده از یک تصویر پایه پایتون
FROM python:3.9-slim

# تنظیمات کاربری و پوشه کاری
WORKDIR /app

# نصب وابستگی‌های سیستم
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev

# کپی کردن فایل requirements.txt به داخل داکر
COPY requirements.txt .

# نصب وابستگی‌ها با استفاده از pip
RUN pip install --no-cache-dir -r requirements.txt

# کپی کردن تمامی فایل‌ها به دایرکتوری کاری
COPY . .

# دستور اجرا برای شروع اپلیکیشن
CMD ["python", "app.py"]
