name: zb56_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - tensorflow
  - scikit-learn
  - flask
  - pip
  - pip:
    - requests
    - matplotlib
